#!/usr/bin/env python3
"""Dependency-free, data-driven static site builder. Run from any directory."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1]
def load(p): return json.loads((R/p).read_text())
committee=load('content/ieee/committee.json'); records=load('content/aisc/portfolio.json'); framework=load('content/aisc/framework.json'); initiatives=load('content/aisc/initiatives.json'); event=load('content/aisc/events.json')[0]
def esc(s):return html.escape(str(s),quote=True)
BASE='/aisc/'
def url(p=''):return BASE+p
NAV=[('about/','About'),('standards/','Standards'),('initiatives/','Initiatives'),('implement/','Implement'),('events/','Events')]
def button(label,path,kind=''):return f'<a class="button {kind}" href="{url(path)}">{label}<span aria-hidden="true">↗</span></a>'
def chips(ids):return '<div class="chips">'+''.join(f'<a class="chip" href="{url("standards/"+i+"/")}">{i}</a>' for i in ids)+'</div>'
def head(kicker,title,desc):return f'<section class="page-head"><div class="wrap"><div class="breadcrumb"><a href="{url()}">Home</a> / {kicker}</div><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{desc}</p></div></section>'
def section(title,body,extra='',kicker=''):
 return f'<section class="section {extra}"><div class="wrap">'+(f'<p class="eyebrow">{kicker}</p>' if kicker else '')+(f'<h2>{title}</h2>' if title else '')+body+'</div></section>'
def page(path,title,body,description='Explore AI standards, strategic initiatives and the four-level framework: Interoperate, Understand, Trust, Govern.'):
 nav=''.join(f'<a href="{url(p)}"'+(' aria-current="page"' if path.startswith(p) else '')+f'>{n}</a>' for p,n in NAV)
 content=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | AISC</title><meta name="description" content="{esc(description)}"><meta name="theme-color" content="#102b37"><meta property="og:title" content="{esc(title)} | AISC"><meta property="og:description" content="{esc(description)}"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='5' fill='%23102b37'/%3E%3Cpath d='M6 24L15 7h3l8 17h-5l-2-5h-8l-2 5zM13 15h5l-2-5z' fill='%23d6f374'/%3E%3C/svg%3E"><link rel="stylesheet" href="{url('assets/site.css')}"><script src="{url('assets/site.js')}" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="utility"><div class="wrap"><span>IEEE Computer Society · Artificial Intelligence Standards Committee</span><span><a href="https://sagroups.ieee.org/ai-sc/">Official IEEE committee site ↗</a></span></div></div><header class="header"><div class="wrap header-inner"><a class="brand" href="{url()}" aria-label="AISC home"><strong>AISC<span style="color:var(--teal)">.</span></strong><small>Artificial Intelligence<br>Standards Committee</small></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav class="nav" id="navigation" aria-label="Main navigation">{nav}<a class="nav-cta" href="{url('participate/')}">Participate ↗</a></nav></div></header><main id="main">{body}</main><footer class="footer"><div class="wrap"><div class="footer-main"><div><a class="brand" href="{url()}"><strong>AISC.</strong></a><p>Interoperate. Understand. Trust. Govern.</p><p>A community information site maintained by Richard Tong. IEEE’s official committee pages remain authoritative for standards, project status and governance.</p></div><div><h3>Explore</h3><a href="{url('framework/')}">Four-level framework</a><a href="{url('standards/')}">Standards explorer</a><a href="{url('communities/')}">Communities & working groups</a><a href="{url('resources/')}">Resources & sources</a></div><div><h3>Connect</h3><a href="{url('participate/')}">Participate in AISC</a><a href="https://sagroups.ieee.org/ai-sc/">Official IEEE AISC ↗</a><a href="https://www.computer.org/">IEEE Computer Society ↗</a><a href="https://standards.ieee.org/">IEEE Standards Association ↗</a></div></div><div class="footer-bottom"><span>IEEE and related marks are trademarks of IEEE. This site is hosted on a personal GitHub Pages account.</span><span>Edition: September 2026 · <a style="display:inline;font-size:inherit" href="{url('resources/#sources')}">Source notes</a></span></div></div></footer></body></html>'''
 dest=R/path/'index.html' if path else R/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(content)

def architecture():
 return '<div class="architecture"><div class="arch-heading"><span>A standards architecture</span><span>01 — 04</span></div>'+''.join(f'<a class="level-band band-{i}" href="{url("framework/#"+l["name"].lower())}"><span class="number">0{i}</span><span><strong>{l["name"]}</strong><small>{l["question"]}</small></span><span aria-hidden="true">↗</span></a>' for i,l in enumerate(framework['levels'],1))+'<p class="arch-note">A proposed portfolio framework · September 2026</p></div>'
def eventcard():
 return f'<article class="event"><div class="date">Nov<strong>03</strong>2026</div><div><span class="badge">Upcoming summit</span><h3>{event["title"]}</h3><p>Seoul, Republic of Korea · 09:00–13:00 KST</p><p>Daisy Room, 5th floor</p></div>{button("Event details","events/seoul-summit/","secondary")}</article>'
def joincta():return '<div class="cta"><h2>Help shape the intelligence<br>we will all depend on.</h2>'+button('Participate in AISC','participate/')+'</div>'
body=f'''<section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">Open systems. Shared understanding. Human control.</p><h1>Standards for AI.<br><em>Agency for people.</em></h1><p class="lead">Building an open, understandable, trustworthy and human-governed AI ecosystem.</p><div class="buttons">{button('Explore the standards','standards/')}{button('Our four-level framework','framework/','secondary')}</div><p class="small">IEEE Computer Society / Artificial Intelligence Standards Committee</p></div>{architecture()}</div></section><div class="ticker"><div class="wrap"><span class="badge lime">Next gathering</span><span><strong>03 Nov 2026</strong> &nbsp; AISC AI Standards Summit · Seoul</span><a href="{url('events/seoul-summit/')}">Explore the summit ↗</a></div></div>'''
body+=section('',f'<div class="section-head"><div><p class="eyebrow">The AI divide is changing</p><h2>Beyond access.<br>Toward agency and control.</h2></div><a class="text-link" href="{url("framework/")}">Explore the framework ↗</a></div><p class="lead">Powerful models are only the beginning. The next questions are whether we can connect, share meaning, verify behavior and retain authority over the intelligence we use.</p><div class="grid four">'+''.join(f'<article class="card framework-card"><span class="card-num">0{i}</span><h3>{l["name"]}</h3><p><strong>{l["question"]}</strong></p><p>{l["description"]}</p><a class="bottom-link" href="{url("framework/#"+l["name"].lower())}">Explore this level ↗</a></article>' for i,l in enumerate(framework['levels'],1))+'</div><p class="small" style="margin-top:20px">Proposed framework for committee discussion; project mappings are illustrative.</p>')
body+=section('',f'<div class="section-head"><div><p class="eyebrow">Portfolio update · 09 September 2026</p><h2>From direction to progress.</h2></div><a class="text-link" href="{url("progress/")}">Read the portfolio update ↗</a></div><div class="grid three"><article class="card"><p class="progress-label">New approvals</p><p class="progress-num">12</p><h3>Newly approved PARs</h3><p>The liaison report records twelve approvals, with eight projects highlighted for SC 42 coordination.</p><a class="bottom-link" href="{url("projects/?status=Newly+approved+PAR")}">Explore highlighted projects ↗</a></article><article class="card"><p class="progress-label">Emerging work</p><p class="progress-num">07</p><h3>Proposals under review</h3><p>New work on AI observability, GenAI lifecycle governance, world-model evaluation and more.</p><a class="bottom-link" href="{url("projects/?status=Under+review")}">See the review snapshot ↗</a></article><article class="card"><p class="progress-label">International coordination</p><p class="progress-num" style="font-size:48px">SC 42</p><h3>A shared standards conversation</h3><p>Coordination topics connect interoperability, semantics, evaluation, trust and governance.</p><a class="bottom-link" href="{url("communities/#liaison")}">Explore coordination themes ↗</a></article></div>','alt')
body+=section('',f'<div class="feature"><div><p class="eyebrow">Featured initiative · Agentic AI</p><h2>Make the ecosystem<br>work together.</h2><p class="lead">Agents need more than a connection. They need identity, shared context, delegated authority and evidence that travels with their work.</p>{chips(["P3394","P3931","P3971","P3427","P3428"])}<div class="buttons">{button("Explore agentic AI","initiatives/agents/","lime")}</div></div><div><div class="diagram-row"><strong>Discover & connect</strong><small>Descriptions · Registries · Interfaces</small></div><div class="diagram-row"><strong>Understand & act</strong><small>Meaning · Context · Delegation</small></div><div class="diagram-row"><strong>Verify & govern</strong><small>Provenance · Evidence · Authority</small></div><p class="small" style="margin-top:20px">An illustrative view of coordination themes.</p></div></div>','dark')
body+=section('',f'<div class="section-head"><div><p class="eyebrow">Strategic initiatives</p><h2>One ecosystem.<br>Connected areas of work.</h2></div><a class="text-link" href="{url("initiatives/")}">View all initiatives ↗</a></div><div class="grid three">'+''.join(f'<article class="card"><span class="badge">Coordination theme</span><h3>{x["title"]}</h3><p>{x["description"]}</p><a class="bottom-link" href="{url("initiatives/"+x["slug"]+"/")}">Explore initiative ↗</a></article>' for x in [initiatives[2],initiatives[3],initiatives[7]])+'</div>')
body+=section('',f'<div class="feature"><div><p class="eyebrow">Standards as products</p><h2>From specification<br>to implementation.</h2><p class="lead">A practical standard needs an ecosystem: profiles, reference implementations, SDKs, conformance tests and feedback from real use.</p>{button("Explore the implementation approach","implement/","secondary")}</div><div class="steps"><div class="step"><div><h3>Specify & build</h3><p>Clear profiles, reference code, adapters and examples.</p></div></div><div class="step"><div><h3>Test & connect</h3><p>Conformance evidence and independent interoperability.</p></div></div><div class="step"><div><h3>Adopt & improve</h3><p>Plugfests, implementation feedback and measurable value.</p></div></div></div></div>','alt')
body+=section('',f'<div class="feature"><div><p class="eyebrow">The long-term question</p><h2>Who controls your<br>accumulated intelligence?</h2></div><div><p class="lead">Cognitive sovereignty means retaining control over knowledge, identity, policies, skills, memory and decisions as models and providers change.</p><span class="badge">Research / exploration</span><p style="margin-top:20px"><a class="text-link" href="{url("about/cognitive-sovereignty/")}">Explore cognitive sovereignty ↗</a></p></div></div>')
body+=section('',f'<div class="section-head"><div><p class="eyebrow">Events & community</p><h2>Build the next chapter together.</h2></div><a class="text-link" href="{url("events/")}">All events ↗</a></div>'+eventcard()+ '<div style="margin-top:40px">'+joincta()+'</div>','alt')
page('','Standards for AI. Agency for people.',body)
# About
body=head('About AISC','A shared foundation for AI.','AISC brings standards work on AI systems, models, data and governance into a common technical community.')
body+=section('',f'<div class="columns"><div><p class="eyebrow">Committee scope · IEEE baseline</p><h2>Governance and practice.</h2><p class="lead">{committee["scope"]}</p><p><a class="text-link" href="{committee["provenance"]["url"]}">Read the official committee scope ↗</a></p><div class="notice">This community site pairs IEEE-sourced committee information with AISC liaison updates and proposed strategic directions. Formal IEEE records govern official status.</div><h2 style="margin-top:45px">Our strategic direction</h2><p>Standardize how AI systems connect, share meaning, earn trust and preserve human control. The September 2026 position paper proposes a four-level lens for understanding the portfolio and identifying gaps.</p>{button("Explore the framework","framework/","secondary")}</div><aside class="sidebar"><h3>Explore AISC</h3><a href="#leadership">Leadership</a><a href="{url("communities/")}">Communities & working groups</a><a href="{url("about/principles/")}">Proposed principles</a><a href="{url("about/cognitive-sovereignty/")}">Cognitive sovereignty</a><a href="https://sagroups.ieee.org/ai-sc/">Official governance & procedures ↗</a></aside></div>')
body+=section('Leadership','<div id="leadership" class="grid three">'+''.join(f'<article class="person"><span class="badge">{o["role"]}</span><h3>{o["name"]}</h3><p>IEEE C/AISC</p></article>' for o in committee['officers'])+'</div><p class="small">Source: official IEEE AISC committee page, verified 25 September 2026.</p>','alt')
page('about/','About AISC',body)
# Framework
body=head('Four-level framework','Interoperate. Understand.<br>Trust. Govern.','From interoperability to cognitive sovereignty: a proposed framework for the societal impact of AI standardization.')
body+=section('', '<div class="notice">September 2026 position paper for committee discussion. This is an illustrative portfolio coordination model, not an official ISO/IEC classification or an adopted IEEE requirement.</div>'+''.join(f'<article class="level-detail" id="{l["name"].lower()}"><span class="card-num">0{i}</span><div><p class="eyebrow">Level {i}</p><h2>{l["name"]}</h2><p class="question">{l["question"]}</p><p class="lead">{l["description"]}</p><p>{l["keywords"]}</p>{chips(l["projects"])}'+('<p class="small" style="margin-top:20px">Governance-related projects provide context; cognitive asset portability and provider exit remain proposed areas for exploration.</p>' if i==4 else '')+'</div></article>' for i,l in enumerate(framework['levels'],1)))
body+=section('Value for three constituencies','<div class="table-wrap"><table><thead><tr><th>Level</th><th>Government</th><th>AI producers</th><th>AI consumers</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+s+'</td>' for s in row)+'</tr>' for row in [('Interoperate','Open digital infrastructure','Larger interoperable markets','Choice and portability'),('Understand','Consistent institutional meaning','Reusable capabilities','AI that fits local context'),('Trust','Measurable assurance','Predictable requirements','Evidence and accountability'),('Govern','Institutional autonomy','Open competition','Ownership, agency and control')])+'</tbody></table></div>','alt')
page('framework/','The four-level framework',body)
# Explorer
for route,title,desc,items in [('standards/','Explore the standards portfolio.','Search selected standards and projects from the September 9 liaison report. Official IEEE pages remain authoritative.',records),('projects/','Active and emerging projects.','Explore ongoing projects, newly approved PARs and proposals under review in the September 9 report.',[r for r in records if r['type']=='project'])]:
 statuses=list(dict.fromkeys(r['status'] for r in items));opts=''.join(f'<option value="{esc(s)}">{esc(s)}</option>' for s in statuses)
 content=head('Standards explorer',title,desc)+section('',f'<div class="notice">Report snapshot: <strong>9 September 2026</strong>. This is a selected portfolio, not the complete IEEE catalog. Live catalog access was unavailable during this build; publication and review statuses have not been upgraded from the report. Four-level mappings are editorial.</div><div class="filters"><label for="search">Search designation, title or topic<input id="search" type="search" placeholder="Try P3394, governance, education…"></label><label for="status">Status<select id="status"><option value="">All statuses</option>{opts}</select></label><label for="level">Framework level<select id="level"><option value="">All levels</option>'+''.join(f'<option>{l["name"]}</option>' for l in framework['levels'])+'</select></label></div><div class="result-meta"><span id="result-count" role="status" aria-live="polite">'+str(len(items))+' records</span><a href="https://sagroups.ieee.org/ai-sc/standards/">Official standards catalog ↗</a></div><div id="results">'+''.join(f'<article class="record" data-search="{esc((r["id"]+" "+r["title"]+" "+r["topic"]).lower())}" data-status="{esc(r["status"])}" data-level="{r["level"]}"><a class="record-id" href="{url("standards/"+r["id"]+"/")}">{r["id"]}</a><div><h3><a href="{url("standards/"+r["id"]+"/")}">{esc(r["title"])}</a></h3><div class="chips"><span class="chip">{r["level"]}</span><span class="chip">{esc(r["topic"])}</span></div></div><div class="record-meta"><span class="badge">{r["status"]}</span><div>As of 09 Sep 2026</div></div></article>' for r in items)+'</div><div id="empty" class="empty" hidden><h3>No matching records</h3><p>Try another search or clear the filters.</p><button id="reset" class="button">Clear filters</button></div><noscript><p>All records are shown below. Enable JavaScript to use search and filters.</p></noscript>')
 page(route,title,content)
for r in records:
 body=head(r['id'],esc(r['title']),'Portfolio record from the AISC liaison report to ISO/IEC JTC 1/SC 42.')
 body+=section('',f'<div class="columns"><div><span class="badge">{r["status"]}</span><h2 style="margin-top:30px">Portfolio context</h2><p>This record is associated with <strong>{esc(r["topic"])}</strong>. Its illustrative primary placement in the four-level framework is <strong>{r["level"]}</strong>.</p><p>Project approval, draft approval and publication are distinct stages. The status shown here reproduces the September 9 report and is not a live certification of current IEEE status.</p><div class="notice">{("This proposal was under IEEE NesCom review as of the report date. It is not presented here as an approved project." if r["status"]=="Under review" else "Check the IEEE canonical record for the latest status and participation details.")}</div><div class="buttons"><a class="button" href="{r["provenance"]["canonical_url"]}">View official IEEE catalog ↗</a>{button("How to participate","participate/","secondary")}</div></div><aside class="sidebar"><h3>Source & status</h3><p class="small">Authority: AISC liaison report<br>Report date: 9 September 2026<br>Framework mapping: editorial<br>Live catalog: not verified</p><a href="{url("resources/#sources")}">Source methodology</a><a href="{url("standards/")}">Back to standards explorer</a></aside></div>')
 page('standards/'+r['id']+'/',r['id']+' — '+r['title'],body)
# Initiatives
body=head('Strategic initiatives','Connected work.<br>Shared direction.','Cross-project coordination themes connect formal standards work with the practical questions facing AI ecosystems.')
body+=section('', '<p class="small">These are editorial groupings based on the liaison report, not a list of separately approved IEEE programs.</p><div class="grid two">'+''.join(f'<article class="card"><span class="badge">{x["status"]}</span><h3>{x["title"]}</h3><p>{x["description"]}</p>{chips(x["projects"])}<a class="bottom-link" href="{url("initiatives/"+x["slug"]+"/")}">Explore initiative ↗</a></article>' for x in initiatives)+'</div>')
page('initiatives/','Strategic initiatives',body)
for x in initiatives:
 body=head('Coordination theme',x['title'],x['description'])
 body+=section('Related portfolio', '<p>Explore the relevant projects and their dated status records.</p>'+chips(x['projects'])+'<div class="notice">Source: AISC liaison report, 9 September 2026. Inclusion here indicates a coordination theme; it does not change a project’s approved scope or status.</div>')
 if x['slug']=='agents':
  body+=section('An interface for an agent ecosystem.','<p class="lead">P3394’s liaison description covers Agent Manifest, Universal Message Format, AI Channel Adapter, AI Identity and Session, together with authorization, lifecycle, provenance and conformance.</p><div class="grid three">'+''.join(f'<article class="card"><h3>{t}</h3><p>{d}</p></article>' for t,d in [('Manifest & discovery','Make an agent’s identity and capabilities discoverable.'),('Messages & channels','Support structured exchanges across different transports.'),('Identity & sessions','Preserve context and represent the authority under which an agent acts.')])+'</div>','alt')
 body+=section('',joincta());page('initiatives/'+x['slug']+'/',x['title'],body)
# Implementation
body=head('Implementation ecosystem','Standards as products.','A proposed implementation approach: connect specifications to usable code, conformance evidence and sustained adoption.')
body+=section('', '<p class="lead">The liaison report and quarterly position paper explore a more practical support model for standards. The elements below describe the intended approach; they are not claims that every project already ships these assets.</p><div class="grid three">'+''.join(f'<article class="card"><span class="card-num">0{i}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate([('Profiles & specifications','Define implementable interfaces, extension mechanisms and versioning rules.'),('Reference implementations','Show how requirements translate into working, reusable software.'),('SDKs & adapters','Reduce integration effort with examples and migration guidance.'),('Conformance tests','Connect requirements to repeatable tests and conformance matrices.'),('Plugfests & feedback','Test independent implementations together and feed evidence back into the work.'),('Adoption & support','Track user value, implementation training and sustained participation.')],1))+'</div>')
body+=section('Bring implementation evidence.','<p class="lead">Working groups are the entry point for reference code, test contributions and interoperability experiments. Ask the relevant group for verified repositories and current contribution guidelines.</p>'+button('Connect with a working group','participate/'),'alt')
page('implement/','Standards as products',body)
# Communities
body=head('Communities','Standards are built together.','Connect with the committee, responsible subcommittees, working groups and international coordination activities.')
body+=section('', '<div class="grid two"><article class="card"><span class="badge">Responsible subcommittee</span><h3>AISC-RSC</h3><p>Chair: George Percivall</p><a class="bottom-link" href="https://sagroups.ieee.org/ai-sc/">Official committee information ↗</a></article><article class="card"><span class="badge">Responsible subcommittee</span><h3>Generative AI & Foundation Models</h3><p>GENAI Chair: Amy Jiang</p><a class="bottom-link" href="https://sagroups.ieee.org/ai-sc/">Official committee information ↗</a></article></div>')
body+=section('Working groups & open source','<p class="lead">Contribute technical requirements, review drafts, develop implementation examples or bring interoperability evidence. Each project follows its working group’s participation process.</p>'+button('Find a project','projects/','secondary')+' '+button('Get involved','participate/'))
body+=section('International coordination','<div id="liaison"><p class="eyebrow">IEEE C/AISC ↔ ISO/IEC JTC 1/SC 42</p><p class="lead">The September 9 liaison report identifies common ground across agent interoperability, semantics, evaluation, governance, observability, edge AI and physical AI.</p><p>These topics are offered for information and discussion. They do not imply a change to either organization’s scope or work programme.</p><a class="text-link" href="'+url('progress/')+'">Read the portfolio update ↗</a></div>','alt')
page('communities/','Communities & international coordination',body)
# Events
page('events/','Events & community',head('Events','Meet. Discuss. Build.','Gatherings that connect standards development, implementation and the wider AI community.')+section('',eventcard())+section('Working group meetings','<p class="lead">Meeting schedules and access details are maintained by individual working groups. Follow the committee or join a project to receive current notices.</p>'+button('How to participate','participate/'),'alt'))
page('events/seoul-summit/','AISC AI Standards Summit — Seoul',head('03 November 2026 · Seoul','AISC AI Standards Summit','An opportunity to connect the standards portfolio, strategic framework and implementation community.')+section('',f'<div class="columns"><div><h2>Meeting details</h2><p><strong>Tuesday, 3 November 2026</strong><br>09:00–13:00 Korea Standard Time (UTC+9)<br>Seoul, Republic of Korea<br>Daisy Room, 5th floor</p><p><strong>For New York participants:</strong><br>Monday, 2 November, 19:00–23:00 EST (UTC−5).</p><div class="notice">{event["venue_note"]} Attendance arrangements and the programme will be updated as organizers confirm them.</div><div class="buttons"><a class="button" href="mailto:richard.tong@ieee.org?subject=AISC%20Seoul%20Summit%20inquiry">Ask about attendance ↗</a><a class="button secondary" href="{url("events/seoul-summit.ics")}" download>Add to calendar ↓</a></div></div><aside class="sidebar"><h3>Organizer update</h3><p class="small">Room reservation confirmed by TTA, as supplied by Richard Tong. Building address, speakers and registration details have not yet been added.</p><a href="{url("framework/")}">Explore the discussion framework</a></aside></div>'))
(R/'events/seoul-summit.ics').write_text('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AISC Community//Summit//EN\r\nBEGIN:VEVENT\r\nUID:aisc-seoul-summit-20261103@neolaf.com\r\nDTSTAMP:20260925T230000Z\r\nDTSTART:20261103T000000Z\r\nDTEND:20261103T040000Z\r\nSUMMARY:AISC AI Standards Summit\r\nLOCATION:Daisy Room (5th floor) - Seoul\r\nDESCRIPTION:Room reserved by TTA. Building address and agenda to be announced.\r\nSTATUS:TENTATIVE\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n')
# Principles & sovereignty
principles=[('Openness','Interfaces should work across models and frameworks without a proprietary critical dependency.'),('Choice & competition','Users should be able to change models, agents or providers.'),('Portability','Accumulated knowledge, workflows, identities and memory should move with their owners.'),('Accountability','Responsibilities should be explicit and supported by evidence.'),('Human & societal control','Oversight points and control boundaries should be visible and testable.')]
page('about/principles/','Proposed principles',head('Position paper · September 2026','What should every standard advance?','Five proposed commitments for portfolio discussion and project review.')+section('', '<div class="steps">'+''.join(f'<div class="step"><div><h3>{t}</h3><p>{d}</p></div></div>' for t,d in principles)+'</div><div class="notice">These are proposed principles from the quarterly framework, not adopted mandatory IEEE criteria.</div>'))
page('about/cognitive-sovereignty/','Cognitive sovereignty',head('Research / exploration','Keep authority over<br>your accumulated intelligence.','Cognitive sovereignty asks whether individuals, organizations and societies retain control as their use of AI deepens.')+section('', '<div class="prose"><h2>What must remain yours?</h2><p class="lead">Knowledge. Identity. Policies. Skills. Memory. Decisions.</p><p>The September position paper asks how these assets can remain portable across models and providers, with explicit rights, oversight and institutional accountability.</p><h2>An open question for future work</h2><p>The paper identifies cognitive asset portability and control boundaries as a gap in the current portfolio. It proposes exploring a study group and scoping a PAR if warranted. This site does not represent that proposal as a chartered group or approved standard.</p><h2>What success could look like</h2><ul><li>Change providers while retaining accumulated knowledge and agent identity.</li><li>Make delegated authority and human intervention points explicit.</li><li>Keep evidence of decisions and responsibility across system boundaries.</li><li>Preserve competition at the model, agent, application and service layers.</li></ul></div>')+section('',joincta(),'alt'))
# Progress
page('progress/','September portfolio update',head('Recent progress · 09 September 2026','A broader portfolio.<br>A more connected ecosystem.','Highlights from the AISC outgoing liaison report to ISO/IEC JTC 1/SC 42.')+section('Newly approved work','<p>The report records twelve PAR approvals and names the following eight as particularly relevant to SC 42 coordination.</p>'+chips([r['id'] for r in records if r['status']=='Newly approved PAR'])+'<h2 style="margin-top:50px">Emerging proposals</h2><p>Seven proposals were under IEEE NesCom review at the report date. Their current approval status requires confirmation from IEEE.</p>'+chips([r['id'] for r in records if r['status']=='Under review'])+'<h2 style="margin-top:50px">Published and approved-draft activity</h2><p>The report includes multimodal LLM applications, organizational governance, model management, inference optimization, AI literacy and Spatial Web work. Individual records preserve the report’s distinctions between publication, approved drafts and reported approval status.</p>'+button('Explore all selected records','standards/','secondary')))
# Participate
page('participate/','Participate in AISC',head('Participate','Your experience belongs<br>in the standards conversation.','Follow the committee, contribute to a working group, or bring evidence from real implementations.')+section('', '<div class="grid three">'+''.join(f'<article class="card"><span class="card-num">0{i}</span><h3>{t}</h3><p>{d}</p><a class="bottom-link" href="{link}">{label} ↗</a></article>' for i,(t,d,link,label) in enumerate([('Follow AISC','Start with the official IEEE participation instructions for committee interests and mailing-list access.','https://sagroups.ieee.org/ai-sc/how-to-participate/','Official participation guide'),('Join a working group','Choose a project that matches your expertise and follow its current participation process.',url('projects/'),'Explore projects'),('Bring a proposal','Discuss a new standards need or implementation contribution with the committee.','mailto:richard.tong@ieee.org?subject=AISC%20participation%20inquiry','Contact the chair')],1))+'</div><div class="notice">Membership, voting eligibility and working group procedures are governed by the applicable IEEE rules. The official participation guide provides the authoritative next steps.</div>'))
# Resources
page('resources/','Resources & source notes',head('Resources','A traceable view of the work.','Official records, dated portfolio updates and clearly identified strategic proposals.')+section('IEEE resources','<div class="grid three">'+''.join(f'<article class="card"><h3>{t}</h3><p>{d}</p><a class="bottom-link" href="{link}">Visit IEEE ↗</a></article>' for t,d,link in [('Committee & governance','Officers, official scope and links to policies and procedures.','https://sagroups.ieee.org/ai-sc/'),('Published standards','The canonical committee standards catalog.','https://sagroups.ieee.org/ai-sc/standards/'),('Active projects','The canonical listing of Project Authorization Requests.','https://sagroups.ieee.org/ai-sc/active-pars/')])+'</div>')+section('Sources & editorial method','<div id="sources" class="prose"><h3>1. IEEE committee baseline</h3><p>Scope and leadership were checked against the official committee homepage on 25 September 2026. The source is maintained separately from editorial content.</p><h3>2. September liaison report</h3><p><em>IEEE AISC SC42 Liaison Report Updated 2874</em>, dated 9 September 2026, supplied by Richard Tong. It is the source of the selected project records, the twelve-PAR milestone, review statuses and coordination themes. Original documents are not republished here.</p><h3>3. Quarterly strategic framework</h3><p><em>AISC Q3 2026 Four-Level Framework</em>, supplied by Richard Tong. The presentation identifies itself as a position paper for committee discussion. Its principles, cognitive-sovereignty exploration and suggested success criteria remain proposals.</p><h3>4. Event information</h3><p>TTA’s confirmation of the Daisy Room reservation was supplied by the organizer through Richard Tong. The full building address and agenda remain pending.</p><h3>Refresh policy</h3><p>IEEE is authoritative for formal status. This edition retains the report’s dated status snapshot because live standards and PAR catalog retrieval could not be verified. Future updates should compare source records, review differences and rebuild the site. A failed retrieval never overwrites verified content.</p><p>Portfolio groupings and four-level placements are editorial aids. An approved PAR is not a published standard. Proposed initiatives are not presented as adopted IEEE requirements.</p></div>','alt'))
print(f'Built {len(list(R.rglob("index.html")))} static pages')
